export enum IngredientCategory {
  VEGETABLES = 'VEGETABLES',
  FRUITS = 'FRUITS',
  MEAT = 'MEAT',
  FISH = 'FISH',
  DAIRY = 'DAIRY',
  GRAINS = 'GRAINS',
  LEGUMES = 'LEGUMES',
  NUTS_AND_SEEDS = 'NUTS_AND_SEEDS',
  OIL_AND_FATS = 'OIL_AND_FATS',
  SPICES = 'SPICES',
  SWEETS = 'SWEETS',
  BEVERAGES = 'BEVERAGES',
  OTHER = 'OTHER'
}
