CREATE TYPE gender AS ENUM ('MALE', 'FEMALE', 'OTHER');
CREATE TYPE diet_type AS ENUM ('KETO', 'VEGAN', 'PALEO', 'BALANCED', 'STANDARD', 'VEGETARIAN', 'MEDITERRANEAN');
CREATE TYPE activity_level AS ENUM ('SEDENTARY', 'LIGHT', 'MODERATE', 'HIGH', 'EXTREME');